version: '{build}'

clone_folder: c:\gopath\src\github.com\AlekSi\gocovermerge

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%PATH%;C:\msys64\mingw64\bin;%GOPATH%\bin

  - go version
  - echo %PATH%
  - go env
  - where mingw32-make
  - where bash
  - where ls

  - go get ./...
  - go get github.com/mattn/goveralls

build_script:
  - mingw32-make install

test_script:
  - mingw32-make

on_success:
  - goveralls -coverprofile=cover.out
  - bash <(curl -s https://codecov.io/bash) -X fix
